module.exports = function( grunt ) {

"use strict";

var uiFiles = [
		"libs/jquery-ui/ui/jquery.ui.core.js",
		"libs/jquery-ui/ui/jquery.ui.widget.js",
		"libs/jquery-ui/ui/jquery.ui.effect.js"
	],
	pluginFiles = [
		// generated by requirejs, banners and comments stripped by concat/uglifyjs
		"dist/coverflow.standalone.js"
	],
	jsFiles = uiFiles.concat( pluginFiles ),
	cssFiles = [
		"src/css/coverflow.css"
	],
	banner = "/*! <%= pkg.title || pkg.name %> - v<%= pkg.version %> - " +
		"<%= grunt.template.today('isoDate') %>\n" +
		"<%= pkg.homepage ? '* ' + pkg.homepage + '\\n' : '' %>" +
		"* Copyright (c) <%= grunt.template.today('yyyy') %> <%= pkg.author.name %>;" +
		" Licensed <%= _.pluck(pkg.licenses, 'type').join(', ') %> */\n",

	uiBanner = "/*! jQuery UI - v1.10.4 - 2014-01-17\n" +
		"* http://jqueryui.com\n"+
		"* Includes: jquery.ui.core.js, jquery.ui.widget.js, jquery.ui.effect.js\n" +
		"* Copyright 2014 jQuery Foundation and other contributors; Licensed MIT */\n",
	// minified files
	minify = {
		options: {
			preserveComments: false
		},
		all: {
			options: {
				banner: banner + uiBanner
			},
			files: {
				"dist/coverflow.min.js": "dist/coverflow.js"
			}
		},
		standalone : {
			options: {
				banner: banner
			},
			files: {
				"dist/coverflow.standalone.min.js": "dist/coverflow.standalone.js"
			}
		}
	},
	minifyCSS = {
		options: {
			keepSpecialComments: 0
		},
		main: {
			options: {
				keepSpecialComments: "*"
			},
			src: "dist/coverflow.css",
			dest: "dist/coverflow.min.css"
		}
	};


// grunt plugins
grunt.loadNpmTasks( "grunt-git-authors" );
grunt.loadNpmTasks( "grunt-autoprefixer" );
grunt.loadNpmTasks( "grunt-contrib-jshint" );
grunt.loadNpmTasks( "grunt-contrib-uglify" );
grunt.loadNpmTasks( "grunt-contrib-concat" );
grunt.loadNpmTasks( "grunt-contrib-qunit" );
grunt.loadNpmTasks( "grunt-contrib-copy");
grunt.loadNpmTasks( "grunt-compare-size" );
grunt.loadNpmTasks( "grunt-contrib-less" );
grunt.loadNpmTasks( "grunt-contrib-watch" );
grunt.loadNpmTasks( "grunt-contrib-requirejs" );

grunt.initConfig({
	pkg: grunt.file.readJSON("package.json"),
	files: {
		dist: "<%= pkg.name %>-<%= pkg.version %>"
	},
	compare_size: {
		all: [
			"dist/coverflow.min.js",
			"dist/coverflow.js"
		]
	},
	concat: {
		js: {
			options: {
				banner: banner + uiBanner,
				stripBanners: {
					block: true
				}
			},
			src: jsFiles,
			dest: "dist/coverflow.js"
		},
		standalone : {
			options: {
				banner: banner,
				stripBanners: {
					block: true
				}
			},
			src: pluginFiles,
			dest: "dist/coverflow.standalone.js"
		},
		css: {
			options: {
				banner: banner,
				stripBanners: {
					block: true
				}
			},
			src: cssFiles,
			dest: "dist/coverflow.css"
		}
	},
	uglify: minify,
	copy: {
		main : {
			files: [{
				src: [
					"AUTHORS.txt",
					"MIT-LICENSE.txt",
					"README.md",
					"package.json"
				],
				dest: "dist/",
				filter: "isFile"
			}]
		}
	},
	qunit: {
		all: [ "tests/qunit/*.html" ]
	},
	jshint: {
		all: {
			options: {
				jshintrc: "src/.jshintrc"
			},
			files: {
				src: "src/js/*.js"
			}
		}
	},
	autoprefixer: {
		all: {
			files: {
				"src/css/coverflow.css" : "src/css/coverflow.unprefixed.css"
			}
		}
	},
	less: {
		dev: {
			options: {
				dumpLineNumbers : true
			},
			files: {
				"src/css/coverflow.unprefixed.css": "src/css/coverflow.less"
			}
		},
		dist : {
			options: {
				cleancss : true
			},
			files: {
				"src/css/coverflow.unprefixed.css": "src/css/coverflow.less"
			}
		}

	},
	watch: {
		css: {
			options : {
				livereload : true
			},
			files: [
				"src/css/**/*.less",
				"src/js/**/*.js",
				"tests/qunit/visual*.html"
			],
			tasks: [ "css" ]
		}
	},
	requirejs: {
		all: {
			options: {
				baseUrl: "src/js/",

				optimize: "none",

				//Finds require() dependencies inside a require() or define call.
				findNestedDependencies: true,

				//If skipModuleInsertion is false, then files that do not use define()
				//to define modules will get a define() placeholder inserted for them.
				//Also, require.pause/resume calls will be inserted.
				//Set it to true to avoid this. This is useful if you are building code that
				//does not use require() in the built project or in the JS files, but you
				//still want to use the optimization tool from RequireJS to concatenate modules
				//together.
				skipModuleInsertion: true,

				mainConfigFile: "src/main.js",

				include: [
					"coverflowjs"
				],

				exclude: [
					"jquery",
					"uiCore",
					"uiWidget",
					"uiEffects"
				],

				//File paths are relative to the build file, or if running a commmand
				//line build, the current directory.
				wrap: {
					startFile: "build/wrap.start",
					endFile: "build/wrap.end"
				},

				out: "dist/coverflow.standalone.js",

				pragmasOnSave: {
					buildExclude: true
				}
			}
		}
	}
});

grunt.registerTask( "default", [ "lint", "test" ] );
grunt.registerTask( "lint", [ "jshint" ] );
grunt.registerTask( "test", [ "qunit" ] );
grunt.registerTask( "css", [ "less:dev", "autoprefixer" ] );
grunt.registerTask( "css:release", [ "less:dist", "autoprefixer", "concat:css" ] );
grunt.registerTask( "build", [
		"css:release",
		"requirejs",
		"concat:js",
		"concat:standalone",
		"copy",
		"uglify"
	]);

};
